### ISSUE TITLE
Suggestion: use of Avocode / Zeplin apps

### ISSUE THREAD

**Issue by hdpero** [silverstripe/silverstripe-ux#2]
Hi,
just thought that use of [Avocode ](https://avocode.com/) or [Zeplin](https://zeplin.io/) apps can help for those that do not have Sketch to view designs. 
Another great thing about those apps is how easy is to inspect design and export images / css variables etc.

**Comment by clarkepaul** [comment]
@hdpero We use InVision to present the designs to non-Sketch users (often linked on GitHub issues), this also has access to the code (for colours, dimensions etc.) although it isn't available to everybody in the community as you need to have an InVision account and be added to the project.

We use DSM for a component overview which is slowly be developed, these are used to help guide the CMS Pattern Library which is currently being built. https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe

We have several InVision projects which makes it hard to share with everyone, a lot of most recent concepts are going into https://invis.io/FTG16IYV5KB 

I'll take a look at Avocode as thats new to me :)
